### ISSUE TITLE
Documentation for command line options?

### ISSUE THREAD

**Issue by philtomson** [cambridgehackers/fpgajtag#2]
Could you add some documentation of the command line options?

**Comment by jankcorn** [comment]
I added more text to the fpgajtag command line 'usage' message.  (printed
when the program is invoked w/o parameters).
How's that?

**Comment by philtomson** [comment]
Ok, so it's:
$ ./src/fpgajtag 
./src/fpgajtag: [ -x ] [ -l ] [ -t ] [ -s <serialno> ] [ -i <index> ] [ -r ] <filename>
Optional arguments:
  -x             Write input file to /dev/xdevcfg on Zynq devices
  -l             Display a list of all jtag interfaces discovered on USB
  -s <serialno>  Use the jtag interface with the given serial number
  -i <index>     Program the 'index' device in the jtag chain that matches the IDCODE in the input file
  -t             Trace usb programming traffic

So <filename> above is a Xilinx .bit file? (and it's directed to a target FPGA with either the -s <serialno> or the -i <index> )

What is the '-c' option used for? I notice you show an example using it in the README.md file. It seems to be for reading in the .jtag files. If I do: "fpgajtag -c foo.jtag" does that send foo.jtag to program the FPGA?

**Comment by jameyhicks** [comment]
I just pushed some more explanation of the operation while programming.

-Jamey
