### ISSUE TITLE
id from file does not match actual id

### ISSUE THREAD

**Issue by RadhikaG** [cambridgehackers/fpgajtag#7]
I'm trying to run the [Connectal echo example](https://github.com/cambridgehackers/connectal/tree/shuotao-vcu118-rebased/examples/echo) on the VCU118; this error message pops up and the process dies without success.
```
fpgajtag: Digilent:Digilent USB Device:210308AE6FD7; bcd:900
[init_fpgajtag] id 20000000 from file does not match actual id 4b31093
subprocess pid 26834 completed status=ff00 255
```

Our FPGA board is connected via JTAG to the host machine running Ubuntu 18.04. The JTAG+Connectal drivers seem to be correctly installed (board shows up in the Vivado Hardware Manager). Is there any reason this message would appear?

**Comment by jameyhicks** [comment]
Hi,

I do not remember if I've tested this with VCU118. I don't think it works.

I've been told that vcu118 Connectal users are using a tcl script to
program via vivado.

**Comment by jameyhicks** [comment]
However, I think I can fix the problem where the wrong ID is read from a bit or bin file.

**Comment by jankcorn** [comment]
It looks like the mkTop.bin file format may have changed.

In src/util.c: read_inputfile(), line 661, the file ID is extracted from the
input file.   In the example, the bogus value '20000000' is being read.

I don't have a license for xcvu9p, so I tried regenerating the file
for the zedboard target, giving:
zedboard$ od -t x1 hw/mkTop.bin|head
0000000 ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
*
0000040 00 00 00 bb 11 22 00 44 ff ff ff ff ff ff ff ff
0000060 aa 99 55 66 20 00 00 00 30 02 20 01 00 00 00 00
0000100 30 02 00 01 00 00 00 00 30 00 80 01 00 00 00 00
0000120 20 00 00 00 30 00 80 01 00 00 00 07 20 00 00 00
0000140 20 00 00 00 30 02 60 01 00 00 00 00 30 01 20 01
0000160 02 00 3f e5 30 01 c0 01 00 00 00 00 30 01 80 01
0000200 03 72 70 93 30 00 80 01 00 00 00 09 20 00 00 00
               ^^  ^^  ^^ ^^.   IDCODE in file

Would it be possible to either get the generated bitfile (hw/mkTop.bin)
or a hex byte dump of the first 1k or so?

Thanks!

**Comment by jameyhicks** [comment]
It looks like the thing to do is scan for 

30018001 Write to IDCODE

and then the next 4 bytes are the IDCODE.

It's at 0xac instead of 0x80 in the ultrascale BIN files.

http://lastweek.io/fpga/bitstream/

**Comment by jankcorn** [comment]
Pushed an fix, parsing the Xilinx configuration bitstream
to extract the IDCODE, instead of just using a fixed offset
(as suggested... thanks!)

Seems to work ok on zedboard and vc108 data.

**Comment by jameyhicks** [comment]
I uploaded a new version to launchpad in case you're installing from the PPA, @RadhikaG
